Lint/NonLocalExitFromIterator:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/LineEndConcatenation:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SymbolProc:
  Enabled: false
