Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 25

Metrics/LineLength:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 11

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/LineEndConcatenation:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SymbolProc:
  Enabled: false
